### PR TITLE
fix(macos): tray icon focus stealing and submenu bugs, add server selection

### LINKED ISSUE #1316: Tray icon menu is binded with app window open
### Operating system

macOS

### System version

Tahoe 26.3.1

### Installation type

zip

### Version

1.1.1

### Description

When I click on the system tray icon to open the menu, the app window opens as well (and Mac switches to that as the active menu), so I lose focus on what I'm doing in a different window.

### Reproduction

Open a full-screen window of an app (like a browser) in macOS, and then click on the Throne system tray icon.

### Logs

```shell

```

### PR DESCRIPTION
**Pull request by AliKarami**
## Summary
- **Fix tray click stealing focus on macOS (#1316):** Disable `ActivateWindow` on tray icon single-click for macOS, preventing the app from coming to foreground when interacting with the tray menu.
- **Fix System Proxy submenu arrow intermittently missing (#1317):** Create a dedicated `QMenu` for the tray's System Proxy options instead of sharing `ui->menu_spmode` between the menu bar and tray, which caused rendering glitches.
- **Add Select Server submenu to tray (#1318):** Dynamically populated submenu that lists profiles grouped by non-archived groups, shows the currently running profile with a checkmark, and allows starting/stopping profiles directly from the tray.

## Test plan
- [ ] macOS: Right-click tray icon — verify System Proxy submenu always shows its arrow and children
- [ ] macOS: Single-click tray icon — verify main window does NOT activate
- [ ] macOS: Open Select Server submenu — verify profiles are listed, grouped correctly, and running profile is checked
- [ ] macOS: Click a profile in Select Server — verify it starts; click Stop — verify it stops
- [ ] Linux/Windows: Verify single-click tray icon still activates the window as before (no regression)

Closes #1316, #1317, #1318

### CODE REVIEW

File: src/ui/mainwindow.cpp [hunk 1]
```diff
@@ -544,8 +599,10 @@ MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent), ui(new Ui::MainWi
     tray->setContextMenu(trayMenu);
     connect(tray, &QSystemTrayIcon::activated, qApp, [=, this](QSystemTrayIcon::ActivationReason reason) {
         if (reason == QSystemTrayIcon::Trigger) {
+#ifndef Q_OS_MAC
```
Comment (Mahdi-zarei) [inline src/ui/mainwindow.cpp]: It is better if we use `getOS()` here and have an if-else. Also this only prevents activating the app window, we should also trigger the context menu here if on darwin.

File: src/ui/mainwindow.cpp [hunk 2]
```diff
@@ -535,7 +535,62 @@ MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent), ui(new Ui::MainWi
...
+                if (!profile) continue;
+                auto *action = targetMenu->addAction(profile->name);
+                action->setCheckable(true);
+                action->setChecked(running && running->id == profile->id);
+                connect(action, &QAction::triggered, this, [=, this]() { profile_start(pid); });
+            }
+        }
+    });
+    trayMenu->addSeparator();
+    // Dedicated System Proxy submenu for tray (avoids sharing ui->menu_spmode)
```
Comment (Mahdi-zarei) [inline src/ui/mainwindow.cpp]: I don't think the bug you have mentioned is caused by a shared sub menu, I need some time to find out what is going on, but i hardly think spawning a new menu helps here.

File: src/ui/mainwindow.cpp [hunk 3]
```diff
@@ -535,7 +535,62 @@ MainWindow::MainWindow(QWidget *parent) : QMainWindow(parent), ui(new Ui::MainWi
     trayMenu->addAction(ui->actionRemember_last_proxy);
     trayMenu->addAction(ui->actionAllow_LAN);
     trayMenu->addSeparator();
-    trayMenu->addMenu(ui->menu_spmode);
+    // Select Server submenu (dynamically populated)
+    trayServerMenu = new QMenu(tr("Select Server"));
```
Comment (Mahdi-zarei) [inline src/ui/mainwindow.cpp:541]: Regarding this sub-menu, i got some points to consider. First, some people have massive count of profiles, so we should only show 10-20 profiles here (starting from the group where the current running profile is from, if no profile is running, starting from the currentGroup)
Second, it is best to have a ↓ and ↑ on the bottom/top of the menu so that if there are more than 10-20 profiles, we can paginate them and make the menu convenient without making it too big.

File: src/ui/mainwindow.cpp (hunk 1 above)
Comment (AliKarami) [reply src/ui/mainwindow.cpp]: Good call, switched to `getOS()` with an if-else, and now on Darwin we trigger `tray->contextMenu()->popup(QCursor::pos())` so the context menu shows on single-click.

File: src/ui/mainwindow.cpp (hunk 2 above)
Comment (AliKarami) [reply src/ui/mainwindow.cpp]: The bug was fixed in the build I tested, but reverted back to `ui->menu_spmode`. Let me know what you find on the root cause.

File: src/ui/mainwindow.cpp (hunk 3 above)
Comment (AliKarami) [reply src/ui/mainwindow.cpp:541]: I've added pagination, profiles are shown 15 per page, starting from the running profile's group (or currentGroup if none running). ↑/↓ actions at the edges let users navigate pages.

**Comment by Mahdi-zarei** [comment]
I looked around and it seems the issue with System proxy menu was caused by MacOS handling menus differently and thus having issues with menus being reused with different parents, so your solution to use a separate menu was correct (although we could reuse the actions). I also made improvements for when there are lots of profiles, so that the select server menu won't be laggy. Please give it a test and if everything works, we can merge it.

**Comment by AliKarami** [comment]
@Mahdi-zarei, seems your changes fixed the problem with the `system proxy` menu, and also the select server and "Stop: server" are working fine.
The only problem here is that when I click on the throne system tray icon, two different menus open simultaneously (the native macOS one overlaps the other, but I should close both after):
Screenshot 1405-01-11 at 22 47 37
Screenshot 1405-01-11 at 22 47 27

**Comment by AliKarami** [comment]
The duplicate context menu is fixed by the previous commit, and I've tested it.
I think you can merge now.

**Comment by Mahdi-zarei** [comment]
Great! Thank you!
